# ---------- Stage 1: Build ----------
FROM node:24-alpine AS build
WORKDIR /app
# Copy dependency files first
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy source code
COPY . .
# Build the production-ready static files
RUN npm run build
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
