services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3304:3306"
    networks:
      - app-network

  backend:
    image: app-backend:latest
    container_name: app-backend
    restart: always
    ports:
      - "5004:5000"
    networks:
      - app-network

  frontend:
    image: app-frontend:latest
    container_name: app-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "84:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
