version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3304:3306"
    networks:
      - app-network

  backend:
    image: app-backend:latest
    container_name: app-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5004:5000"
    networks:
      - app-network

  frontend:
    image: app-frontend:latest
    container_name: app-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "84:80"
    networks:
      - app-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
